export enum Category {
  ELECTRONICS = 'ELECTRONICS',
  CLOTHING = 'CLOTHING',
  APPLIANCES = 'APPLIANCES',
  BOOKS = 'BOOKS',
  BEAUTY = 'BEAUTY',
  SPORTS = 'SPORTS',
  TOYS = 'TOYS',
  FOOD = 'FOOD'
}
