name: Integrations tests

on:
  workflow_run:
    workflows:
      - Unit tests
    types:
      - completed

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          npm run test:integration -- --coverage
      - name: Ensure coverage
        run: |
          npx jest --coverageThreshold='{ "global": { "statements": 80, "branches": 80, "functions": 80, "lines": 80 } }'
