name: Pipeline CI/CD

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check if node_modules exists
        run: |
          if [ ! -d "node_modules" ]; then
            echo "node_modules does not exist!"
            exit 1
          else
            echo "node_modules exists."
          fi
      - name: Build application
        run: |
          echo "Building application..."
          npm run build
      - name: Upload dependencies as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
      - name: Run linter
        run: |
          echo "Running linting..."
          npm run lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: ./node_modules
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          npm run test:unit -- --coverage
      - name: Ensure coverage
        run: |
          npx jest --coverageThreshold='{ "global": { "statements": 80, "branches": 80, "functions": 80, "lines": 80 } }'

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          npm run test:integration -- --coverage
      - name: Ensure coverage
        run: |
          npx jest --coverageThreshold='{ "global": { "statements": 80, "branches": 80, "functions": 80, "lines": 80 } }'
