name: Unit tests

on:
  workflow_run:
    workflows:
      - Build application
    types:
      - completed

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: ./node_modules
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          npm run test:unit -- --coverage
      - name: Ensure coverage
        run: |
          npx jest --coverageThreshold='{ "global": { "statements": 80, "branches": 80, "functions": 80, "lines": 80 } }'
